# Generated by Django 6.0.3 on 2026-03-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='existing_work_url',
            field=models.URLField(blank=True, help_text='Link to your music on YouTube, SoundCloud, Instagram, etc.'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='id_document',
            field=models.FileField(blank=True, help_text='Government ID or passport — stored securely, admin only', null=True, upload_to='verification/ids/'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='real_name',
            field=models.CharField(blank=True, help_text='Legal full name — kept private, admin only', max_length=200),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='verification_note',
            field=models.TextField(blank=True, help_text='Admin note explaining verification decision'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
