# Generated by Django 6.0.3 on 2026-04-10 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('admin_reply', 'Admin Reply'), ('artist_post', 'Artist Announcement'), ('new_follower', 'New Follower'), ('track_liked', 'Track Liked'), ('track_approved', 'Track Approved'), ('track_rejected', 'Track Rejected'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx')],
            },
        ),
    ]
