# Generated by Django 6.0.3 on 2026-03-22 04:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#6366F1', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('album_type', models.CharField(choices=[('single', 'Single'), ('ep', 'EP'), ('album', 'Album')], default='single', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='accounts.artistprofile')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='tracks/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('lyrics', models.TextField(blank=True)),
                ('is_explicit', models.BooleanField(default=False)),
                ('license_type', models.CharField(choices=[('cc_by', 'Creative Commons BY'), ('cc_by_nc', 'Creative Commons BY-NC'), ('all_rights', 'All Rights Reserved')], default='all_rights', max_length=20)),
                ('bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('waveform_data', models.JSONField(blank=True, default=list)),
                ('preview_start', models.PositiveIntegerField(default=0, help_text='Preview start in seconds')),
                ('is_published', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='accounts.artistprofile')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.genre')),
                ('tags', models.ManyToManyField(blank=True, related_name='tracks', to='music.tag')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
