# Generated by Django 6.0.3 on 2026-03-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.UUIDField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('listened_duration', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_track_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ArtistStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('new_followers', models.PositiveIntegerField(default=0)),
                ('top_track_id', models.UUIDField(blank=True, null=True)),
                ('revenue_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('artist_id', 'date')},
            },
        ),
    ]
